[platformio]
default_envs = esp32dev
test_dir = test/native

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

[env:native]
platform = native
test_framework = googletest
test_build_src = yes
build_flags =
  -std=gnu++17
  -DUNIT_TEST_NATIVE
  -I test/support/native/include
